introduction to SKlearn(scikitlearn)
uses important functions of library

#steps needed to be followed
#1. end-end scikit learn workflow
#2.Getting data ready 
#3.choosing the right algorithm
#4..Evaluating the model
#5.Improving the model
#6..save and load  the trained model
#7..putting it all together

# SCI-KIT Learn workflow

In [2]:
#1 getting  the data ready
import pandas as pd
import numpy as np
heart=pd.read_csv("heart-disease.csv")
heart

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [3]:
#creating the X variable(feature matrix)

X=heart.drop("target",axis=1) #independent variable

#creating the Y variable (Labels) 

y=heart["target"] #dependent variable

In [4]:
#as this is classification we need to choose the right model and hyperparameters

from sklearn.ensemble import RandomForestClassifier 
clf=RandomForestClassifier(n_estimators=100)
clf.get_params() #to see the parameters

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [5]:
#fitting the model to the training data

from sklearn.model_selection import train_test_split
X_test,X_train,y_test,y_train=train_test_split(X,y , test_size=0.2,)

In [6]:
clf.fit(X_train,y_train)

RandomForestClassifier()

In [7]:
#make a predicition
X_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
154,39,0,2,138,220,0,1,152,0,0.0,1,0,2
45,52,1,1,120,325,0,1,172,0,0.2,2,0,2
264,54,1,0,110,206,0,0,108,1,0.0,1,1,2
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,61,1,0,138,166,0,0,125,1,3.6,1,1,2
276,58,1,0,146,218,0,1,105,0,2.0,1,1,3
253,67,1,0,100,299,0,0,125,1,0.9,1,2,2
219,48,1,0,130,256,1,0,150,1,0.0,2,2,3
69,62,0,0,124,209,0,1,163,0,0.0,2,0,2

In [8]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
203,68,1,2,180,274,1,0,150,1,1.6,1,0,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
97,52,1,0,108,233,1,1,147,0,0.1,2,3,3
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1
100,42,1,3,148,244,0,0,178,0,0.8,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,56,1,0,125,249,1,0,144,1,1.2,1,1,2
230,47,1,2,108,243,0,1,152,0,0.0,2,0,2
283,40,1,0,152,223,0,1,181,0,0.0,2,0,3
185,44,1,0,112,290,0,0,153,0,0.0,2,1,2
119,46,0,0,138,243,0,0,152,1,0.0,1,0,2

In [9]:
#preds is a conventional name for making the predictions
y_preds=clf.predict(X_test)
y_preds

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [10]:
y_test

299    0
154    1
45     1
264    0
151    1
      ..
279    0
276    0
253    0
219    0
69     1
Name: target, Length: 242, dtype: int64

In [11]:
 #evaluating the  model
#to check how well the model is trained (on the train & test data)
clf.score(X_train,y_train)

1.0

In [12]:
clf.score(X_test,y_test)

0.7933884297520661

In [13]:
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_preds))

[[ 89  15]
 [ 35 103]]

In [14]:
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.72      0.86      0.78       104
           1       0.87      0.75      0.80       138

    accuracy                           0.79       242
   macro avg       0.80      0.80      0.79       242
weighted avg       0.81      0.79      0.79       242

In [15]:
print(accuracy_score(y_test,y_preds))

0.7933884297520661

In [16]:
#5. improving the model 
#trying different n_parameters to check in which prameters does the model givingg the best accuracy rate

np.random.seed(30)
for i in range(10,100,10):
    print(f"trying model with {i} estimators")
    clf=RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print("model accuracy on test data" ,{clf.score(X_test,y_test)})
    print(" ")

trying model with 10 estimators
model accuracy on test data {0.756198347107438}

trying model with 20 estimators
model accuracy on test data {0.768595041322314}

trying model with 30 estimators
model accuracy on test data {0.7644628099173554}

trying model with 40 estimators
model accuracy on test data {0.7727272727272727}

trying model with 50 estimators
model accuracy on test data {0.8140495867768595}

trying model with 60 estimators
model accuracy on test data {0.8016528925619835}

trying model with 70 estimators
model accuracy on test data {0.7975206611570248}

trying model with 80 estimators
model accuracy on test data {0.7975206611570248}

trying model with 90 estimators
model accuracy on test data {0.8057851239669421}

In [17]:
#to save the model 
import pickle 
pickle.dump(clf,open("Loaded_model_1.pk","wb"))

In [18]:
load = pickle.load(open("Loaded_model_1.pk","rb"))
load.score(X_test,y_test)

0.8057851239669421